# Generated by Django 2.1.4 on 2018-12-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weburls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraurl',
            options={'ordering': ('created',)},
        ),
    ]
