# Generated by Django 2.1.4 on 2018-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weburls', '0003_auto_20181228_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='on_portal_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
